# Generated by Django 5.2.6 on 2025-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
