# Generated by Django 5.2.6 on 2025-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_experience_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
