# Generated by Django 5.2.6 on 2025-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_education_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
