# Generated by Django 5.2.6 on 2025-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0004_skill_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_demo_url',
        ),
        migrations.AlterField(
            model_name='education',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
