# Generated by Django 5.2.6 on 2025-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0005_remove_project_live_demo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True),
        ),
    ]
